cargo-features = ["profile-rustflags"]

[package]
name = "aura_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.50.0", features = ["rt-multi-thread", "fs", "time", "signal", "parking_lot"] }
tokio-util = { version = "0.7.18", features = ["io"] }

tracing = { version = "0.1.44", features = ["max_level_info"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["std", "ansi", "fmt"] }

tonic = { version = "0.14.5", default-features = false, features = ["server", "router", "gzip"] }
tonic-reflection = "0.14.5"
tower_governor = { version = "0.8.0", default-features = false, features = ["tonic"] }

surrealdb = "3.0.4"

jsonwebtoken = "10.3.0"
argon2 = "0.6.0-rc.8"
nanoid = "0.5.0"

boml = "2.0.0"
dashmap = "7.0.0-rc2"
lettre = "0.11.21"
fastrand = "2.4.1"

aura_rust = { git = "https://github.com/kyber-technologies/aura_proto.git" }

[features]
default = []
testing = []
